USE DATABASE AI_ENGINEERING_LAB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE SUPPORT_TICKETS (
    TICKET_ID INTEGER,
    CUSTOMER_NAME STRING,
    SUBJECT STRING,
    MESSAGE STRING,
    CREATED_AT TIMESTAMP_NTZ
);