USE DATABASE AI_ENGINEERING_LAB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE SUPPORT_TICKET_STAGE;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

COPY INTO SUPPORT_TICKETS
FROM @SUPPORT_TICKET_STAGE
FILE_FORMAT = CSV_FORMAT;