USE DATABASE AI_ENGINEERING_LAB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS CUSTOMER_SUPPORT_TICKETS (
    TICKET_ID STRING,
    CUSTOMER_NAME STRING,
    CUSTOMER_EMAIL STRING,
    TICKET_SUBJECT STRING,
    TICKET_DESCRIPTION STRING,
    ISSUE_CATEGORY STRING,
    PRIORITY_LEVEL STRING,
    TICKET_CHANNEL STRING,
    SUBMISSION_DATE STRING,
    RESOLUTION_TIME_HOURS INTEGER,
    ASSIGNED_AGENT STRING,
    SATISFACTION_SCORE INTEGER
);