USE DATABASE AI_ENGINEERING_LAB;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS CUSTOMER_SUPPORT_CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

COPY INTO CUSTOMER_SUPPORT_TICKETS
FROM @CUSTOMER_SUPPORT_STAGE
FILE_FORMAT = CUSTOMER_SUPPORT_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';