USE DATABASE AI_ENGINEERING_LAB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CUSTOMER_SUPPORT_TICKETS AS
SELECT
    TICKET_ID,
    CUSTOMER_NAME,
    CUSTOMER_EMAIL,
    TICKET_SUBJECT,
    TICKET_DESCRIPTION,
    ISSUE_CATEGORY,
    PRIORITY_LEVEL,
    TICKET_CHANNEL,
    TRY_TO_TIMESTAMP_NTZ(SUBMISSION_DATE) AS SUBMISSION_DATE,
    RESOLUTION_TIME_HOURS,
    ASSIGNED_AGENT,
    SATISFACTION_SCORE
FROM AI_ENGINEERING_LAB.RAW.CUSTOMER_SUPPORT_TICKETS
WHERE
    TICKET_ID IS NOT NULL
    AND TICKET_DESCRIPTION IS NOT NULL
    AND RESOLUTION_TIME_HOURS >= 0
    AND SATISFACTION_SCORE BETWEEN 1 AND 5;