USE DATABASE AI_ENGINEERING_LAB;
USE SCHEMA RAW;

-- 1. Total row count
SELECT COUNT(*) AS TOTAL_ROWS
FROM CUSTOMER_SUPPORT_TICKETS;

-- 2. Duplicate Ticket IDs
SELECT
    TICKET_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM CUSTOMER_SUPPORT_TICKETS
GROUP BY TICKET_ID
HAVING COUNT(*) > 1;

-- 3. Invalid priority values
SELECT DISTINCT PRIORITY_LEVEL
FROM CUSTOMER_SUPPORT_TICKETS
WHERE PRIORITY_LEVEL NOT IN ('Low', 'Medium', 'High', 'Critical');

-- 4. Invalid satisfaction score
SELECT COUNT(*) AS INVALID_SATISFACTION
FROM CUSTOMER_SUPPORT_TICKETS
WHERE SATISFACTION_SCORE NOT BETWEEN 1 AND 5;

-- 5. Negative resolution time
SELECT COUNT(*) AS INVALID_RESOLUTION_TIME
FROM CUSTOMER_SUPPORT_TICKETS
WHERE RESOLUTION_TIME_HOURS < 0;

-- 6. Missing important fields
SELECT COUNT(*) AS MISSING_REQUIRED_FIELDS
FROM CUSTOMER_SUPPORT_TICKETS
WHERE TICKET_ID IS NULL
   OR TICKET_DESCRIPTION IS NULL
   OR CUSTOMER_EMAIL IS NULL;

-- 7. Invalid dates
SELECT COUNT(*) AS INVALID_DATES
FROM CUSTOMER_SUPPORT_TICKETS
WHERE TRY_TO_TIMESTAMP_NTZ(SUBMISSION_DATE) IS NULL;