USE DATABASE AI_ENGINEERING_LAB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE SUPPORT_OPERATION_METRICS AS
SELECT
    ISSUE_CATEGORY,
    TICKET_CHANNEL,
    PRIORITY_LEVEL,
    COUNT(*) AS TICKET_COUNT,
    ROUND(AVG(RESOLUTION_TIME_HOURS), 2) AS AVG_RESOLUTION_HOURS,
    ROUND(AVG(SATISFACTION_SCORE), 2) AS AVG_SATISFACTION_SCORE,
    SUM(
        CASE
            WHEN PRIORITY_LEVEL IN ('High', 'Critical') THEN 1
            ELSE 0
        END
    ) AS HIGH_PRIORITY_TICKETS
FROM AI_ENGINEERING_LAB.CURATED.CUSTOMER_SUPPORT_TICKETS
GROUP BY
    ISSUE_CATEGORY,
    TICKET_CHANNEL,
    PRIORITY_LEVEL;