USE DATABASE AI_ENGINEERING_LAB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE SUPPORT_SLA_RISK AS
SELECT
    TICKET_ID,
    ISSUE_CATEGORY,
    PRIORITY_LEVEL,
    TICKET_CHANNEL,
    RESOLUTION_TIME_HOURS,
    SATISFACTION_SCORE,
    CASE
        WHEN PRIORITY_LEVEL = 'Critical'
             AND RESOLUTION_TIME_HOURS > 12 THEN 'HIGH_RISK'

        WHEN PRIORITY_LEVEL = 'High'
             AND RESOLUTION_TIME_HOURS > 24 THEN 'HIGH_RISK'

        WHEN PRIORITY_LEVEL = 'Medium'
             AND RESOLUTION_TIME_HOURS > 48 THEN 'MEDIUM_RISK'

        WHEN SATISFACTION_SCORE <= 2 THEN 'MEDIUM_RISK'

        ELSE 'LOW_RISK'
    END AS SLA_RISK_LEVEL
FROM AI_ENGINEERING_LAB.CURATED.CUSTOMER_SUPPORT_TICKETS;